import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "motion-safe:scroll-smooth bg-white antialiased",
        inter.className
      )}
    >
      <body className="min-h-screen antialiased bg-slate-50 dark:bg-slate-900">
        <Providers>
          <NextTopLoader height={5} />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
